apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbase-master
  namespace: hbase
spec:
  selector:
    matchLabels:
      app: hbase-master
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hbase-master
    spec:
      containers:
      - name: hbase-master
        image: edmundguo/hbase-hadoop:2.0
        ports:
        - containerPort: 16000          
        volumeMounts:
        - name: hadoop-etc
          mountPath: /etc/hadoop
        - name: hbase-etc
          mountPath: /etc/hbase
        imagePullPolicy: IfNotPresent
        args: 
            ["zookeeper"]
      volumes:
        - name: hadoop-etc
          configMap:
            name: hadoop-etc-vol
        - name: hbase-etc
          configMap:
            name: hbase-etc-vol
  
