apiVersion: v1
kind: Service
metadata:
  name: hbase-master
  namespace: hbase
  labels:
    app: hbase-master
spec:
  ports:
  - port: 16000
    name: server
  - port: 16010
    name: http
  clusterIP: None
  selector:
    app: hbase-master
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hbase-master
  namespace: hbase
spec:
  selector:
    matchLabels:
      app: hbase-master
  serviceName: hbase-master
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: hbase-master
    spec:
      containers:
      - name: hbase-master
        imagePullPolicy: Always
        image: "edmundguo/hbase-hadoop:2.0"
        resources:
          requests:
            memory: "1Gi"
        args: 
            ["master"]            
        ports:
        - containerPort: 16000
          name: server
        - containerPort: 16010
          name: http
        volumeMounts:
          - name: hadoop-etc
            mountPath: /etc/hadoop
          - name: hbase-etc
            mountPath: /etc/hbase          
      volumes:
        - name: hadoop-etc
          configMap:
            name: hadoop-etc-vol
        - name: hbase-etc
          configMap:
            name: hbase-etc-vol
