apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbase-regionserver
  namespace: hbase
spec:
  selector:
    matchLabels:
      app: hbase-regionserver
  strategy:
    type: Recreate
  replicas: 10     
  template:
    metadata:
      labels:
        app: hbase-regionserver
    spec:
      containers:
      - name: hbase-regionserver
        image: edmundguo/hbase-hadoop:2.0
        ports:
        - containerPort: 16020
          name: server
        - containerPort: 16030
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: 16010
          initialDelaySeconds: 60
          periodSeconds: 60
        volumeMounts:
        - name: hadoop-etc
          mountPath: /etc/hadoop
        - name: hbase-etc
          mountPath: /etc/hbase
        imagePullPolicy: IfNotPresent
        args:
            ["regionserver"]
#      securityContext:
#        runAsUser: 1000
#        fsGroup: 1000            
      volumes:
        - name: hadoop-etc
          configMap:
            name: hadoop-etc-vol
        - name: hbase-etc
          configMap:
            name: hbase-etc-vol